apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx1app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1app
  template:
    metadata:
      labels:
        app: nginx1app 
    spec:
      containers:
        - name: nginx1app 
          image: cricdevpcbho-gvebf7fjbsf7fvav.azurecr.io/nginx1app
          ports:
          - containerPort: 80